export const FETCHED_CARDS = 'FETCHED_CARDS'
export const ADDED_USER_CARD = 'ADDED_USER_CARD'
export const FETCHED_USER_CARDS = 'FETCHED_USER_CARDS'
export const FILTERS_SET = 'FILTERS_SET'
export const PAGE_SIZE_SET = 'PAGE_SIZE_SET'
export const PAGE_SET = 'PAGE_SET'
export const RESET = 'RESET'
export const REMOVED_CARDS = 'REMOVED_CARDS'
